// interconnect_inject.js
// Final Code node ("Code — Inject") for the Interconnect Publisher workflow.
// Pulls STRUCTURED JSON from upstream nodes and injects it into the LOCKED design
// template via string replacement. NO HTML is generated by AI — the shell is fixed.
//
// UPSTREAM FIELD CONTRACT (what each node must provide):
//   Set Metadata        -> json: { dateline, vol, no }
//   Generate Lede       -> Claude API response; parsed JSON: { lede: string }
//   Generate Signals    -> Claude API response; parsed JSON: array of
//                          { iso, location, category, headline, detail, angle, variant }
//                          variant: '' (standard) | 'flag' (risk) | 'gold' (opportunity)
//                          iso: PJM | WECC | MISO | ERCOT | CAISO | NYISO | SPP
//   Generate Connectors -> Claude API response; parsed JSON: array of
//                          { demand_market, demand_text, supply_market, supply_text }
//   Fetch Queue Records -> Airtable rows, mapped here:
//                          project <- 'Project Name', iso <- 'Region', type <- 'Generation Type',
//                          mw <- 'MW Capacity', status <- 'Status', poi <- 'POI Name'
//
// OUTPUT: json: { html, filename, vol, no, dateline }
//   filename = "interconnect-vol{vol}-no{no}.html"  (GitHub node writes to interconnect/{filename})
//
// NOTE: TEMPLATE below is a verbatim copy of the locked design shell at
//   interconnect/template/the_interconnect_TEMPLATE.html
// If you edit that file, re-sync this constant. The template must contain no
// backtick or ${ } sequences (it does not today).

const TEMPLATE = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>The Interconnect&#8482; — {{DATELINE}}</title>
<style>
:root {
  --ink:    #16191d;
  --muted:  #54606e;
  --faint:  #8a93a1;
  --line:   #d8dce4;
  --accent: #0b5d4e;
  --a-soft: #e7f2ef;
  --gold:   #a06d18;
  --g-soft: #f9f1de;
  --flag:   #8b2020;
  --paper:  #fdfcfa;
  --data:   #1a3a6b;
  --d-soft: #eaf0f8;
}
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

body {
  font-family: Georgia, "Times New Roman", serif;
  color: var(--ink);
  background: #d6d2cb;
  line-height: 1.6;
  padding: 32px 12px 56px;
  -webkit-font-smoothing: antialiased;
}

.sheet {
  max-width: 840px;
  margin: 0 auto;
  background: var(--paper);
  box-shadow: 0 6px 40px rgba(20,24,31,.22);
}

/* ── MASTHEAD ── */
.masthead {
  padding: 32px 44px 20px;
  border-bottom: 3px double var(--ink);
}
.kicker {
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 9px;
  letter-spacing: 4px;
  text-transform: uppercase;
  color: var(--accent);
  font-weight: 700;
  margin-bottom: 8px;
}
.masthead h1 {
  font-size: 58px;
  letter-spacing: -2px;
  line-height: .93;
  font-weight: 700;
  margin-bottom: 12px;
}
.masthead h1 em {
  font-style: normal;
  color: var(--accent);
}
.masthead h1 sup {
  font-size: 22px;
  vertical-align: super;
  letter-spacing: 0;
  color: var(--accent);
}
.tagline {
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 13px;
  color: var(--muted);
  line-height: 1.45;
  max-width: 560px;
  margin-bottom: 18px;
}

/* ── DATELINE BAR ── */
.dateline-bar {
  display: flex;
  justify-content: space-between;
  align-items: baseline;
  padding: 10px 44px;
  border-top: 1px solid var(--ink);
  border-bottom: 2px solid var(--ink);
  background: var(--paper);
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 10.5px;
  letter-spacing: .5px;
}
.dateline-bar .vol {
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 1.5px;
}
.dateline-bar .vol span {
  font-weight: 400;
  color: var(--muted);
  margin-left: 8px;
}
.dateline-bar .site {
  color: var(--muted);
  font-size: 9.5px;
  letter-spacing: 2px;
  text-transform: uppercase;
}

/* ── BODY ── */
.body-wrap {
  padding: 36px 44px;
}

/* ── LEDE ── */
.lede {
  font-size: 16.5px;
  line-height: 1.65;
  color: var(--ink);
  margin-bottom: 28px;
  padding-bottom: 24px;
  border-bottom: 1px solid var(--line);
}

/* ── SECTION LABELS ── */
.section-label {
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 8.5px;
  font-weight: 700;
  letter-spacing: 3.5px;
  text-transform: uppercase;
  color: var(--accent);
  margin-bottom: 14px;
  padding-bottom: 5px;
  border-bottom: 1px solid var(--accent);
  display: inline-block;
}

/* ── SIGNAL CARDS ── */
.signal-card {
  border-left: 3px solid var(--accent);
  padding: 16px 18px;
  margin-bottom: 18px;
  background: #fafaf8;
}
.signal-card.flag {
  border-left-color: var(--flag);
}
.signal-card.gold {
  border-left-color: var(--gold);
  background: var(--g-soft);
}
.signal-card .signal-meta {
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 9px;
  letter-spacing: 2px;
  text-transform: uppercase;
  color: var(--faint);
  margin-bottom: 6px;
}
.signal-card .signal-meta .badge {
  display: inline-block;
  padding: 1px 7px;
  border-radius: 2px;
  font-size: 8.5px;
  font-weight: 700;
  letter-spacing: 1.5px;
  margin-right: 6px;
}
.badge-pjm  { background: var(--d-soft); color: var(--data); }
.badge-wecc { background: var(--a-soft); color: var(--accent); }
.badge-miso { background: #f0eaf8;       color: #4a2080; }
.badge-ercot{ background: #fef0e0;       color: #8a4400; }
.badge-caiso{ background: #fde8e8;       color: var(--flag); }
.signal-card h3 {
  font-size: 16px;
  font-weight: 700;
  line-height: 1.3;
  margin-bottom: 8px;
  color: var(--ink);
}
.signal-card p {
  font-size: 13.5px;
  color: var(--muted);
  line-height: 1.6;
  margin-bottom: 8px;
}
.signal-card .angle {
  font-size: 13px;
  color: var(--ink);
  font-style: italic;
  border-top: 1px solid var(--line);
  padding-top: 8px;
  margin-top: 4px;
}
.signal-card .angle strong {
  font-style: normal;
  color: var(--accent);
  font-size: 9px;
  letter-spacing: 2px;
  text-transform: uppercase;
  display: block;
  margin-bottom: 3px;
}

/* ── CONNECTOR MARKETS ── */
.connector-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 16px;
  margin-bottom: 24px;
}
.connector-cell {
  padding: 14px 16px;
  background: var(--a-soft);
  border: 1px solid #c2ddd8;
}
.connector-cell.demand { background: var(--g-soft); border-color: #d8c48a; }
.connector-cell .cell-label {
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 8px;
  font-weight: 700;
  letter-spacing: 3px;
  text-transform: uppercase;
  color: var(--accent);
  margin-bottom: 6px;
}
.connector-cell.demand .cell-label { color: var(--gold); }
.connector-cell h4 { font-size: 14px; font-weight: 700; margin-bottom: 4px; }
.connector-cell p  { font-size: 12px; color: var(--muted); line-height: 1.5; }

/* ── QUEUE SPOTLIGHT ── */
.queue-table {
  width: 100%;
  border-collapse: collapse;
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 11.5px;
  margin-bottom: 8px;
}
.queue-table th {
  background: var(--ink);
  color: #fff;
  padding: 7px 10px;
  text-align: left;
  font-size: 8.5px;
  letter-spacing: 2px;
  text-transform: uppercase;
  font-weight: 600;
}
.queue-table td {
  padding: 7px 10px;
  border-bottom: 1px solid var(--line);
  color: var(--ink);
  vertical-align: top;
}
.queue-table tr:nth-child(even) td { background: #f5f4f1; }
.queue-table .mw { font-weight: 700; color: var(--data); }

/* ── DIVIDER ── */
.section-divider {
  border: none;
  border-top: 1px solid var(--line);
  margin: 32px 0;
}

/* ── FOOTER ── */
.footer {
  background: var(--ink);
  color: #8a93a1;
  padding: 24px 44px;
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-size: 10.5px;
  line-height: 1.7;
}
.footer a { color: #b0bcc8; text-decoration: none; }
.footer strong { color: #d0d8e0; }

@media (max-width: 600px) {
  .masthead, .dateline-bar, .body-wrap, .footer { padding-left: 20px; padding-right: 20px; }
  .masthead h1 { font-size: 38px; }
  .connector-grid { grid-template-columns: 1fr; }
}
</style>
</head>
<body>
<div class="sheet">

  <!-- MASTHEAD -->
  <div class="masthead">
    <div class="kicker">NexPhase Advisory &nbsp;·&nbsp; Power Market Intelligence</div>
    <h1>The <em>Inter</em>connect<sup>&#8482;</sup></h1>
    <p class="tagline">Weekly intelligence on power procurement, interconnection queues, and data center development — for teams building at the grid edge.</p>
  </div>

  <!-- DATELINE BAR -->
  <div class="dateline-bar">
    <div class="vol">{{DATELINE}} <span>· Vol. {{VOL}}, No. {{NO}}</span></div>
    <div class="site">NexPhaseAdvisory.net</div>
  </div>

  <!-- BODY -->
  <div class="body-wrap">

    <!-- LEDE -->
    <p class="lede">{{LEDE}}</p>

    <!-- SIGNALS SECTION -->
    <div class="section-label">This Week's Signals</div>
    {{SIGNAL_CARDS}}

    <hr class="section-divider">

    <!-- CONNECTOR MARKETS -->
    <div class="section-label">Connector Markets</div>
    <div class="connector-grid">
      {{CONNECTOR_MARKETS}}
    </div>

    <hr class="section-divider">

    <!-- QUEUE SPOTLIGHT -->
    <div class="section-label">Queue Spotlight</div>
    <table class="queue-table">
      <thead>
        <tr>
          <th>Project</th>
          <th>ISO</th>
          <th>Type</th>
          <th>MW</th>
          <th>Status</th>
          <th>POI / Substation</th>
        </tr>
      </thead>
      <tbody>
        {{QUEUE_ROWS}}
      </tbody>
    </table>

  </div><!-- /body-wrap -->

  <!-- FOOTER -->
  <div class="footer">
    <strong>NexPhase Advisory</strong> &nbsp;·&nbsp; Power Market Intelligence<br>
    Questions or comments: <a href="mailto:info@nexphaseadvisory.net">info@nexphaseadvisory.net</a><br><br>
    This publication is provided for informational purposes only. Nothing herein constitutes legal, financial, or investment advice.
    All queue data derived from public ISO sources. &copy; {{YEAR}} NexPhase Advisory. All rights reserved.<br><br>
    To unsubscribe, reply with "unsubscribe" in the subject line.
  </div>

</div><!-- /sheet -->
</body>
</html>`;

// ---------- helpers ----------
function claudeJSON(resp) {
  // resp is the raw Anthropic /v1/messages response object from a Generate node.
  try {
    const content = (resp && resp.content) || [];
    const text = content.filter(b => b && b.type === 'text').map(b => b.text).join('').trim();
    const cleaned = text.replace(/```json|```/g, '').trim();
    return JSON.parse(cleaned);
  } catch (e) {
    return null;
  }
}
function esc(s) {
  return String(s == null ? '' : s)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}
const ISO_BADGE = { PJM: 'badge-pjm', WECC: 'badge-wecc', MISO: 'badge-miso', ERCOT: 'badge-ercot', CAISO: 'badge-caiso', NYISO: 'badge-pjm', SPP: 'badge-pjm' };
function badgeClass(iso) { return ISO_BADGE[String(iso || '').toUpperCase()] || 'badge-pjm'; }
// Queue "ISO" derived from the Utility field (queue table has no true ISO field).
function isoFromUtility(u) {
  const s = String(u || '');
  if (/PJM/i.test(s)) return 'PJM';
  if (/CAISO/i.test(s)) return 'CAISO';
  if (/MISO/i.test(s)) return 'MISO';
  if (/FPL|Duke|Southeast/i.test(s)) return 'SERC';
  return s; // default: utility value as-is
}

// ---------- pull upstream ----------
const meta = $('Set Metadata').first().json;
const ledeObj = claudeJSON($('Generate Lede').first().json) || { lede: '' };
const signals = claudeJSON($('Generate Signals').first().json) || [];
const connectors = claudeJSON($('Generate Connectors').first().json) || [];
const queueRaw = $('Fetch Queue Records').all().map(i => i.json);

// ---------- build SIGNAL_CARDS ----------
const signalCards = (Array.isArray(signals) ? signals : []).map(s => {
  const variant = (s.variant === 'flag' || s.variant === 'gold') ? ' ' + s.variant : '';
  return '<div class="signal-card' + variant + '">\n' +
    '      <div class="signal-meta">\n' +
    '        <span class="badge ' + badgeClass(s.iso) + '">' + esc(s.iso) + '</span>\n' +
    '        ' + esc(s.location) + ' · ' + esc(s.category) + '\n' +
    '      </div>\n' +
    '      <h3>' + esc(s.headline) + '</h3>\n' +
    '      <p>' + esc(s.detail) + '</p>\n' +
    '      <div class="angle">\n' +
    '        <strong>The Angle</strong>\n' +
    '        ' + esc(s.angle) + '\n' +
    '      </div>\n' +
    '    </div>';
}).join('\n');

// ---------- build CONNECTOR_MARKETS (each pairing = demand cell + supply cell) ----------
const connectorCells = (Array.isArray(connectors) ? connectors : []).map(c => {
  return '<div class="connector-cell demand">\n' +
    '        <div class="cell-label">Demand Signal</div>\n' +
    '        <h4>' + esc(c.demand_market) + '</h4>\n' +
    '        <p>' + esc(c.demand_text) + '</p>\n' +
    '      </div>\n' +
    '      <div class="connector-cell">\n' +
    '        <div class="cell-label">Supply Context</div>\n' +
    '        <h4>' + esc(c.supply_market) + '</h4>\n' +
    '        <p>' + esc(c.supply_text) + '</p>\n' +
    '      </div>';
}).join('\n');

// ---------- build QUEUE_ROWS (map Airtable fields; cap for spotlight) ----------
const QUEUE_CAP = 8;
const queueRows = queueRaw.map(q => ({
  project: q['Project Name'] || q['POI Name'] || '',
  iso: isoFromUtility(q['Utility']),
  type: q['Generation Type'] || q['Project Type'] || '',
  mw: (q['MW Capacity'] != null ? q['MW Capacity'] : ''),
  status: q['Status'] || '',
  poi: q['POI Name'] || ''
}))
  .sort((a, b) => (parseFloat(b.mw) || 0) - (parseFloat(a.mw) || 0))
  .slice(0, QUEUE_CAP)
  .map(q =>
    '<tr>\n' +
    '          <td>' + esc(q.project) + '</td>\n' +
    '          <td>' + esc(q.iso) + '</td>\n' +
    '          <td>' + esc(q.type) + '</td>\n' +
    '          <td class="mw">' + esc(q.mw) + '</td>\n' +
    '          <td>' + esc(q.status) + '</td>\n' +
    '          <td>' + esc(q.poi) + '</td>\n' +
    '        </tr>'
  ).join('\n');

// ---------- inject ----------
const year = new Date().getFullYear();
const html = TEMPLATE
  .split('{{DATELINE}}').join(esc(meta.dateline))
  .split('{{VOL}}').join(esc(meta.vol))
  .split('{{NO}}').join(esc(meta.no))
  .split('{{LEDE}}').join(esc(ledeObj.lede))
  .split('{{SIGNAL_CARDS}}').join(signalCards)
  .split('{{CONNECTOR_MARKETS}}').join(connectorCells)
  .split('{{QUEUE_ROWS}}').join(queueRows)
  .split('{{YEAR}}').join(String(year));

const filename = 'interconnect-vol' + meta.vol + '-no' + meta.no + '.html';

return [{ json: { html, filename, vol: meta.vol, no: meta.no, dateline: meta.dateline } }];
